name: Scrape Politicians

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: |
          cd scraper
          npm install

      - run: |
          cd scraper
          node index.js

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "auto update politicians" || echo "no changes"
          git push
